// ignore_for_file: non_constant_identifier_names, constant_identifier_names

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final PADDING_SMALL_HEIGHT = SizedBox(height: 12.r);
final PADDING_MEDIUM_HEIGHT = SizedBox(height: 18.r);
final PADDING_LARGE_HEIGHT = SizedBox(height: 24.r);

final PADDING_SMALL_WIDTH = SizedBox(width: 12.r);
final PADDING_MEDIUM_WIDTH = SizedBox(width: 18.r);
final PADDING_LARGE_WIDTH = SizedBox(width: 24.r);

const ALERT_DURATION = Duration(seconds: 1);

const API_BASE_URL = "https://backend.nittany-guide.tech/";
const UPLOAD_API_ENDPOINT = 'upload';
const RECOMMEND_API_ENDPOINT = 'recommend';

const MAJORS = [
  'Accounting',
  'Accelerated Premedical-Medical Program (BS/MD)',
  'Acting',
  'Actuarial Science',
  'Advertising & Public Relations',
  'Aerospace Engineering',
  'African American Studies',
  'African Studies',
  'Agribusiness Management',
  'Agricultural & Extension Education',
  'Agricultural and Biorenewable Systems Management',
  'Agricultural Science',
  'Agricultural Sciences (Undecided)',
  'American Studies',
  'Animal Science',
  'Anthropological Science',
  'Anthropology',
  'Architectural Engineering',
  'Architecture (5-Year)',
  'Art B.A.',
  'Art B.F.A.',
  'Art Education',
  'Art History',
  'Asian Studies',
  'Astronomy and Astrophysics',
  'Biobehavioral Health',
  'Biochemistry and Molecular Biology',
  'Biological Engineering',
  'Biology',
  'Biomedical Engineering',
  'Biotechnology',
  'Business',
  'Business Economics',
  'Chemical Engineering',
  'Chemistry',
  'Chinese',
  'Civil Engineering',
  'Classics and Ancient Mediterranean Studies',
  'Communication Arts and Sciences B.A.',
  'Communication Arts and Sciences B.S.',
  'Communication Sciences and Disorders',
  'Communications',
  'Community, Environment and Development',
  'Comparative Literature',
  'Computer Engineering',
  'Computer Science',
  'Corporate Communication',
  'Corporate Innovation and Entrepreneurship',
  'Creative Writing',
  'Criminal Justice B.A.',
  'Criminal Justice B.S.',
  'Criminology B.A.',
  'Criminology B.S.',
  'Cybersecurity Analytics and Operations',
  'Data Sciences, Applied Data Sciences',
  'Data Sciences, Computational Data Sciences',
  'Data Sciences, Statistical Modeling Data Sciences',
  'Digital Arts and Media Design',
  'Digital Journalism and Media',
  'Digital Media, Arts, and Technology',
  'Digital Multimedia Design',
  'Division of Undergraduate Studies',
  'Earth & Mineral Sciences (Undecided)',
  'Earth Science and Policy',
  'Earth Sciences',
  'Economics B.A.',
  'Economics B.S.',
  'Education (Undecided)',
  'Education and Public Policy',
  'Electrical and Computer Engineering Technology',
  'Electrical Engineering',
  'Electrical Engineering Technology',
  'Electro - Mechanical Engineering Technology',
  'Elementary and Early Childhood Education',
  'Elementary Education',
  'Energy and Sustainability Policy B.A.',
  'Energy and Sustainability Policy B.S.',
  'Energy Engineering',
  'Energy, Business and Finance',
  'Engineering (Undecided)',
  'Engineering B.S.',
  'Engineering Science',
  'English',
  'Enterprise Technology Integration',
  'Environmental Resource Management',
  'Environmental Science',
  'Environmental Studies B.A.',
  'Environmental Studies B.S.',
  'Environmental Systems Engineering',
  'Exploratory (Division of Undergraduate Studies)',
  'Film Production',
  'Finance',
  'Food Science',
  'Forensic Science',
  'Forest Ecosystem Management',
  'French and Francophone Studies B.A.',
  'French and Francophone Studies B.S.',
  'Functional Data Analytics',
  'General Arts & Sciences',
  'Geobiology',
  'Geography B.A.',
  'Geography B.S.',
  'Geosciences B.A.',
  'Geosciences B.S.',
  'German B.A.',
  'German B.S.',
  'Global and International Studies B.A.',
  'Global and International Studies B.S.',
  'Global Studies',
  'Graphic Design',
  'Health & Human Development (Undecided)',
  'Health Humanities B.A.',
  'Health Humanities B.S.',
  'Health Policy and Administration',
  'History',
  'Hospitality Management',
  'Human Capital Management',
  'Human Development and Family Studies',
  'Human-Centered Design and Development',
  'Humanities',
  'Immunology and Infectious Disease',
  'Industrial Engineering',
  'Information Sciences and Technology B.S.',
  'Information Systems',
  'Information Technology',
  'Integrated Social Sciences',
  'Integrative Arts',
  'Interdisciplinary Business with Engineering Studies',
  'Interdisciplinary Science and Business',
  'International Business',
  'International Politics',
  'Italian B.A.',
  'Italian B.S.',
  'Japanese',
  'Jewish Studies',
  'Journalism',
  'Kinesiology',
  'Korean',
  'Labor and Human Resources B.A.',
  'Labor and Human Resources B.S.',
  'Landscape Architecture',
  'Landscape Contracting',
  'Latin American Studies',
  'Law and Society (World Campus, Penn State Online)',
  'Liberal Arts (Undecided)',
  'Linguistics',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Materials Science & Engineering',
  'Mathematical Sciences B.S.',
  'Mathematics B.A.',
  'Mathematics B.S.',
  'Mechanical Engineering',
  'Mechanical Engineering Technology',
  'Media Studies',
  'Medieval Studies',
  'Meteorology and Atmospheric Science',
  'Microbiology',
  'Middle East Studies',
  'Middle Level Education',
  'Mining Engineering',
  'Music B.A.',
  'Music B.M.',
  'Music Education',
  'Musical Arts',
  'Musical Theatre, B.F.A.',
  'Multidisciplinary Studies',
  'Nuclear Engineering',
  'Nursing',
  'Nursing (for Registered Nurses)',
  'Nursing (Second Degree Option)',
  'Nutritional Sciences',
  'Occupational Science',
  'Organizational and Professional Communication B.A.',
  'Organizational and Professional Communication B.S.',
  'Organizational Leadership B.A.',
  'Organizational Leadership B.S.',
  'Petroleum and Natural Gas Engineering',
  'Pharmacology and Toxicology',
  'Philosophy B.A.',
  'Philosophy B.S.',
  'Physics',
  'Planetary Science and Astronomy',
  'Plant Sciences',
  'Plastics Engineering Technology',
  'Political Science B.A.',
  'Political Science B.S.',
  'Polymer Engineering and Science',
  'Premedical-Medical (Accelerated Program BS/MD)',
  'Premedicine',
  'Professional Photography',
  'Project and Supply Chain Management',
  'Psychological and Social Sciences B.A.',
  'Psychological and Social Sciences B.S.',
  'Psychology B.A.',
  'Psychology B.S.',
  'Public Policy',
  'Race and Ethnic Studies',
  'Rail Transportation Engineering',
  'Recreation, Park and Tourism Management',
  'Recreation, Park and Tourism Management',
  'Recreation, Park and Tourism Management (Online)',
  'Rehabilitation and Human Services',
  'Risk Management',
  'Russian',
  'Science (Undecided)',
  'Science B.S.',
  'Science Business / M B A',
  'Secondary Education, Mathematics',
  'Secondary Education, Social Studies',
  'Security and Risk Analysis',
  'Social Data Analytics',
  'Social Work',
  'Sociology B.A.',
  'Sociology B.S.',
  'Software Engineering',
  'Spanish B.A.',
  'Spanish B.S.',
  'Special Education',
  'Statistics',
  'Strategic Communications',
  'Structural Design and Construction Engr Technology',
  'Supply Chain and Information Systems',
  'Surveying Engineering',
  'Technical Theatre B.F.A.',
  'Telecommunications and Media Industries',
  'Theatre Studies B.A.',
  'Turfgrass Science',
  'Undecided (Division of Undergraduate Studies)',
  'Veterinary and Biomedical Sciences',
  'Visual Arts Studies',
  'Wildlife and Fisheries Science',
  'Women\'s Studies B.A.',
  'Women\'s Studies B.S.',
  'Workforce Education and Development',
  'World Languages Education',
  'Writing and Digital Media',
];

const CAMPUSES = [
  'Abington',
  'Altoona',
  'Beaver',
  'Behrend',
  'Berks',
  'Brandywine',
  'Dubois',
  'Fayette',
  'Greater allegheny',
  'Harrisburg',
  'Hazleton',
  'Lehigh valley',
  'Mont alto',
  'New kensington',
  'Schuylkill',
  'Scranton',
  'Shenango',
  'University park',
  'Wilkes-barre',
  'World campus',
  'York'
];
